config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/_landing' => 'static_pages#_landing'
  get 'static_pages/home' => 'static_pages#home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations'}

  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  resources :users, only: %i[show index] do
    get '/friend_requests', to: 'friend_requests#index'
    get '/friends', to: 'friendships#index'
  end

  resources :friend_requests, only: %i[create update destroy]
  resources :friendships, only: :destroy
  resources :posts, only: %i[create destroy]
  resources :likes, only: %i[create destroy]
  resources :comments, only: %i[create update destroy]

  root 'static_pages#home'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user, presence: true
  validates :post, presence: true
  validates :content, presence: true, length: { maximum: 400 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :correct_user, only: :destroy

  def create
    @comment = current_user.comments.build(comment_params)
    if @comment.save
      flash[:success] = "Comment posted."
    else
      flash[:danger] = 'Could not comment on post.'
    end
    redirect_to request.referrer
  end

  def destroy
    @comment = Comment.find(params[:id]).destroy
    flash[:info] = "Comment deleted."
    redirect_to request.referrer
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end

  def correct_user
    @comment = current_user.comments.find_by(id: params[:id])
    redirect_to root_url if @comment.nil?
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<li class="media">
  <div class="content">
    <div class="media-left">
      <%= gravatar_for(comment.user, size: 80, classes: 'media-object') %>
    </div>
    <div class="media-body">
      <h5 class="media-haeding"><%= link_to comment.user.name, user_path(comment.user), class: 'text-info' %></h5>
      <p><%= comment.content %></p>
      <p class="text-muted">Posted <%= time_ago_in_words(comment.created_at) %> ago.</p>

      <% if current_user.comments.include?(comment) %>
        <%= link_to 'Delete', comment_path(comment.id), method: :delete, class: 'btn btn-danger btn-raised btn-sm' %>
      <% end %>
    </div>
  </div>
</li>

app/views/comments/_comment_form.html.erb
<div class="content">
  <%= form_for(Comment.new) do |f| %>
    <%= f.hidden_field :post_id, value: post.id %>
    <div class="form-group">
      <%= f.text_area :content, placeholder: "Your thoughts?", class: 'form-control' %>
    </div>
    <%= f.submit 'Comment', class: 'btn btn-primary btn-sm btn-raised' %>
  <% end %>
</div>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>