config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/_landing' => 'static_pages#_landing'
  get 'static_pages/home' => 'static_pages#home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations'}

  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  resources :users, only: %i[show index] do
    get '/friend_requests', to: 'friend_requests#index'
    get '/friends', to: 'friendships#index'
  end

  resources :friend_requests, only: %i[create update destroy]
  resources :friendships, only: :destroy
  resources :posts, only: %i[create destroy]
  resources :likes, only: %i[create destroy]
  resources :comments, only: %i[create update destroy]

  root 'static_pages#home'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :friend_requests, dependent: :destroy
  has_many :pending_friends, through: :friend_requests, source: :friend

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  has_many :posts, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  has_many :comments, dependent: :destroy
  has_many :posts_commented, through: :comments, source: :post

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  # Password validations handled by devise gem
  # Email presence, format, uniqueness handled by devise gem
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, length: { maximum: 255 }

  def num_of_friend_requests
    FriendRequest.where(friend: self).count
  end

  def remove_friend(friend)
    friends.destroy(friend)
  end

  def like(post)
    liked_posts << post
  end

  def unlike(post)
    liked_posts.delete(post)
  end

  def feed
    Post.where("user_id IN (?) OR user_id = ?", friend_ids, id)
  end

    # For OmniAuth Facebook login
    def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    UserMailer.welcome_email(resource).deliver_now
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @feed_items = @user.posts
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size: 250, classes: 'img-raised')
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name,
                            class: "img-circle img-responsive #{classes}",
                            id: 'profile-image')
  end
end

app/views/users/_favorite.html.erb
<div class="card">
  <div class="content">
    <li class="media">
      <div class="media-left">
        <%= gravatar_for(favorite.user, size: 80, classes: 'media-object') %>
      </div>
      <div class="media-body">
        <h4 class="media-header"><%= link_to favorite.user.name, user_path(favorite.user) %></h4>
        <p><%= favorite.content %></p>
      </div>
    </li>
  </div>
</div>

app/views/users/_friend.html.erb
<div class="card">
  <div class="content">
    <li class="media">
      <div class="media-left">
        <%= gravatar_for(friend, size: 100, classes: 'media-object') %>
      </div>
      <div class="media-body">
        <h4 class="media-heading"><%= link_to friend.name, user_path(friend) %></h4>

        <% if current_user.friends.include?(friend) %>
          <%= link_to "Remove friend", friendship_path(friend), method: :delete, class: "btn btn-danger btn-raised" %>
        <% else %>
          <%= render 'users/send_friend_request', user: friend %>
        <% end %>

      </div>
    </li>
  </div>
</div>

app/views/users/_like.html.erb
<%= link_to likes_path(post_id: post.id), method: :post, class: 'btn btn-primary btn-just-icon' do %>
  <i class="fa fa-heart-o"></i>
<% end %>

app/views/users/_send_friend_request.html.erb
<% if current_user.pending_friends.include?(user) || user.pending_friends.include?(current_user) %>
  <button class="btn btn-default disabled">Friend request sent</button>
<% elsif user.friends.include?(current_user) %>
  <h4 class="text-info">You are friends!</h4>
<% else %>
  <%= link_to 'Send friend request', friend_requests_path(friend_id: user.id), method: :post, class: 'btn btn-primary btn-raised' %>
<% end %>

app/views/users/_unlike.html.erb
<%= link_to like_path(post.id), method: :delete, class: 'btn btn-primary btn-just-icon' do %>
  <i class="fa fa-heart"></i>
<% end %>

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>

<div class="header header-filter" style="background: linear-gradient(to right, #feac5e, #c779d0, #4bc0c8);"></div>
  <div class="main main-raised">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="text-center">All Users</h2>
          <%= will_paginate %>
          <ul class="list-group">
            <% @users.each do |user| %>
              <%= render 'users/friend', friend: user %>
            <% end %>
          </ul>
          <%= will_paginate %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% content_for :features, "profile-page" %>
<% content_for :class, "profile-page" %>
<%= provide(:title, "#{@user.name}'s Profile") %>

<div class="header header-filter" style="background: linear-gradient(to right, #feac5e, #c779d0, #4bc0c8);"></div>
  <div class="main main-raised">
    <div class="profile-content">
        <div class="container">
          <div class="row">

            <div class="profile">
              <div class="col-md-3">
                <%= render 'shared/user_info', user: @user %>
                <% unless @user == current_user  %>
                  <%= render 'send_friend_request', user: @user %>
                <% end %>
              </div>
            </div>

            <div class="col-md-8 col-md-offset-1">
              <div class="text-center">
                <h3 class="title text-primary"><%= @user.name %>'s Posts</h3>
              </div>
              <%= render @feed_items %>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>