config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/_landing' => 'static_pages#_landing'
  get 'static_pages/home' => 'static_pages#home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations'}

  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  resources :users, only: %i[show index] do
    get '/friend_requests', to: 'friend_requests#index'
    get '/friends', to: 'friendships#index'
  end

  resources :friend_requests, only: %i[create update destroy]
  resources :friendships, only: :destroy
  resources :posts, only: %i[create destroy]
  resources :likes, only: %i[create destroy]
  resources :comments, only: %i[create update destroy]

  root 'static_pages#home'
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'

  validates :user, presence: true
  validates :friend, presence: true, uniqueness: { scope: :user }

  validate :not_self
  validate :not_friends
  validate :not_pending

  # Builds friendship and deletes friend request
  def accept_friend
    user.friends << friend
    friend.friends << user
    destroy
  end

  private

  def not_self
    errors.add(:friend, "can't be equal to user") if user == friend
  end

  def not_friends
    errors.add(:friend, 'is already added') if user.friends.include?(friend)
  end

  def not_pending
    errors.add(:friend, 'already requested friendship') if friend.pending_friends.include?(user)
  end
end

app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController
  before_action :set_friend_request, except: %i[index create]

  def index
    @received = FriendRequest.where(friend: current_user)
    @sent = current_user.friend_requests
  end

  def create
    friend = User.find(params[:friend_id])
    @friend_request = current_user.friend_requests.build(friend: friend)

    if @friend_request.save
      flash[:success] = 'Friend request sent.'
    else
      flash[:danger] = 'Friend request could not be sent.'
    end
    redirect_to request.referrer
  end

  def update
    @friend_request.accept_friend
    flash[:success] = 'Friend request accepted.'
    redirect_to user_friend_requests_path(current_user)
  end

  def destroy
    @friend_request.destroy
    flash[:info] = 'Friend request declined.'
    redirect_to user_friend_requests_path(current_user)
  end

  private

  def set_friend_request
    @friend_request = FriendRequest.find(params[:id])
  end
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/views/friend_requests/_received.html.erb
<ul class="media-group">
  <% @received.each do |request| %>
    <div class="card">
      <div class="content">
        <li class="media">
          <div class="media-left">
            <%= gravatar_for(request.user, size: 100, classes: 'media-object') %>
          </div>
          <div class="media-body">
            <h4 class="media-heading"> <%= link_to request.user.name, user_path(request.user) %> wants to be your friend.</h4>
            <div class="btn-group">
              <%= link_to 'Accept', friend_request_path(request.id), method: :patch, class: 'btn btn-info btn-raised btn-sm' %>
              <%= link_to 'Decline', friend_request_path(request.id), method: :delete, class: 'btn btn-danger btn-simple btn-sm' %>
            </div>
          </div>
        </li>
      </div>
    </div>
  <% end %>
</ul>

app/views/friend_requests/_sent.html.erb
<ul class="media-group">
  <% @sent.each do |request| %>
    <div class="card">
      <div class="content">
        <li class="media">
          <div class="media-left">
            <%= gravatar_for(request.friend, size: 100, classes: 'media-object') %>
          </div>
          <div class="media-body media-middle">
            <h4 class="media-heading"><%= link_to request.friend.name, user_path(request.friend) %></h4>
          </div>
        </li>
      </div>
    </div>
  <% end %>
</ul>

app/views/friend_requests/index.html.erb
<% provide(:title, "Friend Requests") %>

<div class="header header-filter" style="background: linear-gradient(to right, #feac5e, #c779d0, #4bc0c8);"></div>
  <div class="main main-raised">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h2 class="text-center">Friend Requests</h2>
            <ul class="nav nav-pills nav-justified">
              <li class="active">
                <a href="#received" data-toggle="tab" aria-expanded="true">
                  <i class="material-icons">call_received</i>
                  Receieved
                </a>
              </li>
              <li class="">
                <a href="#sent" data-toggle="tab" aria-expanded="false">
                  <i class="material-icons">call_made</i>
                  Sent
                </a>
              </li>
            </ul>

            <div id="myTabContent" class="tab-content">
              <div class="tab-pane fade active in" id="received">
                <% if @received.empty? %>
                  <div class="content">
                    <h4>You have no received requests.</h4>
                  </div>
                <% else %>
                  <%= render 'received' %>
                <% end %>
              </div>
              <div class="tab-pane fade" id="sent">
                <% if @sent.empty? %>
                  <div class="content">
                    <h4>You have no sent requests.</h4>
                  </div>
                <% else %>
                  <%= render 'sent' %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>