config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/_landing' => 'static_pages#_landing'
  get 'static_pages/home' => 'static_pages#home'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks',
                                    registrations: 'users/registrations'}

  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  resources :users, only: %i[show index] do
    get '/friend_requests', to: 'friend_requests#index'
    get '/friends', to: 'friendships#index'
  end

  resources :friend_requests, only: %i[create update destroy]
  resources :friendships, only: :destroy
  resources :posts, only: %i[create destroy]
  resources :likes, only: %i[create destroy]
  resources :comments, only: %i[create update destroy]

  root 'static_pages#home'
end

app/views/layouts/_base.html.erb
<!doctype html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <%= csrf_meta_tags %>

    <title>Material Kit by Creative Tim</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= favicon_link_tag 'apple-icon.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '76x76' %>
    <%= favicon_link_tag 'favicon.png', rel: 'icon', type: 'image/png' %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag '//fonts.googleapis.com/icon?family=Material+Icons' %>
    <%= stylesheet_link_tag '//fonts.googleapis.com/css?family=Roboto:300,400,500,700' %>
    <%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= yield :head %>
  </head>
  <body class="<%= yield :class %>" data-features="<%= yield :features %>">
    <%= yield %>
  </body>
</html>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <nav class="pull-left">
      <ul>
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'Contact', contact_path %></li>
        <li><a href="https://github.com/holdercp/odin-facebook">Source</a></li>
      </ul>
    </nav>
    <div class="copyright pull-right">
      &copy; 2016, Theme made with <i class="fa fa-heart heart"></i> by Creative Tim
    </div>
  </div>
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-transparent navbar-absolute" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <% if user_signed_in? %>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      <% end %>
      <%= link_to 'Friend Space', root_path, class: 'navbar-brand' %>
    </div>

    <% if user_signed_in? %>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
        <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to root_path do %>
                <i class="material-icons">home</i>
                Home
              <% end %>
            </li>
            <li>
              <%= link_to user_friend_requests_path(current_user) do %>
                <i class="material-icons">inbox</i>
                Friend requests
                <span class="badge"><%= current_user.num_of_friend_requests %></span>
              <% end %>
            </li>
            <li>
              <%= link_to users_path do %>
                <i class="material-icons">group</i>
                Find friends
              <% end %>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="material-icons">account_circle</i><%= current_user.name %><span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to 'Friends', user_friends_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to "Edit Info", edit_user_registration_path(current_user) %></li>
                <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>

        </ul>
      </div>
    <% end %>
  </div>
  <%= render 'shared/flash_messages' unless flash.empty? %>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <%= csrf_meta_tags %>

    <title><%= yield(:title) %> | Friend Space</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag '//fonts.googleapis.com/icon?family=Material+Icons' %>
    <%= stylesheet_link_tag '//fonts.googleapis.com/css?family=Roboto:300,400,500,700' %>
    <%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= yield :head %>
  </head>

  <body class="<%= yield :class %>" data-features="<%= yield :features %>">
    <%= render 'layouts/header' %>
    <div class="wrapper">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' unless content_for :devise_view %>
  </body>
</html>